### ISSUE TITLE
"less wrong" way

### ISSUE THREAD

**Issue by JaoNoctus** [JaoNoctus/phpXablau#1]
###### TODO
- [x] [Namespaces](http://php.net/manual/pt_BR/language.namespaces.php)
- [x] [Use](http://php.net/manual/pt_BR/language.namespaces.importing.php)
- [x] [Autoload](http://php.net/manual/pt_BR/language.oop5.autoload.php)

**Comment by JaoNoctus** [comment]
solved by 3fe421274f7fdbeab1034a96596a49cedb1490ba
